#:schema node_modules/wrangler/config-schema.json
name = "realmkit"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "zzworld-db"
database_id = "7b3fba7f-5aa8-40a3-b149-5449d304a1ea"
